const ENVIRONMENT_KEYS = [
  'BLOCK_DIST_TAG',
  'CONTEXT_PATH',
  'ENVIRONMENT',
  'FUSION_RELEASE',
  'allowedImageDomains',
  'playerRoot',
  'resizerURL',
  'searchKey',
  'videoEnv',
  'videoOrg',
];

const SITE_PROPERTY_KEYS = [
  'aspectRatios',
  'breakpoints',
  'chartBeatAccountId',
  'chartBeatDomain',
  'comscoreID',
  'copyrightText',
  'dangerouslyInjectJS',
  'dateLocalization',
  'dfpId',
  'facebookAdmins',
  'facebookPage',
  'fallbackImage',
  'fontUrl',
  'gaID',
  'galleryCubeClicks',
  'gtmID',
  'imageWidths',
  'locale',
  'navBarBackground',
  'navColor',
  'primaryLogo',
  'primaryLogoAlt',
  'querylyId',
  'querylyOrg',
  'resizerURL',
  'rssUrl',
  'taboolaPublisherId',
  'taboolaWidgets',
  'twitterUsername',
  'websiteDomain',
  'websiteName',
];

const TREE_KEYS = [
  'children',
  'collection',
  'props',
  'type',
];

// documenting all saved keys
// const ALL_KEYS = [
//  "BLOCK_DIST_TAG",
//  "CONTEXT_PATH",
//  "ENVIRONMENT",
//  "FUSION_RELEASE",
//  "allowedImageDomains",
//  "arcSite",
//  "aspectRatios",
//  "breakpoints",
//  "collection",
//  "copyrightText",
//  "dangerouslyInjectJS",
//  "dateLocalization",
//  "deployment",
//  "dfpId",
//  "facebookPage",
//  "fallbackImage",
//  "fontUrl",
//  "imageWidths",
//  "locale",
//  "nativoIntegration",
//  "navBarBackground",
//  "outputType",
//  "playerRoot",
//  "primaryLogo",
//  "primaryLogoAlt",
//  "props",
//  "query",
//  "querylyId",
//  "querylyOrg",
//  "resizerURL",
//  "rssUrl",
//  "searchKey",
//  "source",
//  "taboolaPublisherId",
//  "taboolaWidgets",
//  "twitterUsername",
//  "type",
//  "videoEnv",
//  "videoOrg",
//  "websiteAdPath",
//  "websiteDomain",
//  "websiteName",
//  "children",
//  "contentCache",
//  "globalContent",
// ]

export {
  ENVIRONMENT_KEYS,
  SITE_PROPERTY_KEYS,
  TREE_KEYS,
}
